package minggu;
/*
 * This source file was generated by the Gradle 'init' task
 */
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class App {
    public static void main(String[] args) {
        String appName = "Praktikum Minggu 7";
        int width = 600;
        int height = 400;

        JFrame frame = new JFrame(appName);

        JPanel panel = new JPanel();
        JTextField username = new JTextField();
        username.setText("Masukkan Username: ");
        frame.add(panel);
        frame.add(username);

        frame.setSize(width, height);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}
